# general
Region      = "aws"
Environment = "prod"
Port 	    = 4000

#mongodb
MongoURL = "dev:k9lc4G1k32nyD72@sjc-mongos1.objectrocket.com:24129/koding"

#etcd
Machines = ["http://10.0.0.127:4001,http://10.0.0.128:4001,http://10.0.0.126:4001"]

# signing/generating token
PrivateKey = "files/prod_kontrol_rsa_private.pem"
PublicKey  = "files/prod_kontrol_rsa_public.pem"
