Mongo              = "192.168.59.103:27017/koding"
Environment        = "dev"
Region             = "dev"
Hostname           = "http://lvh.me:8090"

[postgres]
Host=     "192.168.59.103"
Port=     5432
Username= "socialapplication"
Password= "socialapplication"
DBName=   "social"

[mq]
Host     = "192.168.59.103"
Port     = 5672
Login    = "guest"
Password = "guest"
Vhost    = "/"

[redis]
URL = "192.168.59.103:6379"
DB  = 0

[email]
Host            = "lvh.me:8090"
Protocol        = "http:"
DefaultFromMail = "hello@koding.com"
DefaultFromName = "Koding"
ForcedRecipient = "canthefason@gmail.com"
Username        = "koding"
Password        = "DEQl7_Dr"
TemplateRoot    = "workers/emailnotifier/templates/"

[sitemap]
RedisDB = 0

[algolia]
AppId          = "DYVV81J2S1"
ApiKey         = "303eb858050b1067bcd704d6cbfb977c"
ApiSecretKey   = "041427512bcdcd0c7bd4899ec8175f46"
IndexSuffix    = ".dev"

[mixpanel]
Enabled       = false
Token         = "113c2731b47a5151f4be44ddd5af0e7a"

[limits]
MessageBodyMinLen    = 1
PostThrottleDuration = "10s"
PostThrottleCount    = 100

EventExchangeName ="BrokerMessageBus"
DisableCaching    = false
Debug             = false
