Mongo              = "dev:k9lc4G1k32nyD72@10.0.0.239:27017/koding"
Environment        = "prod"
Region             = "prod"
Hostname           = "prod.koding.com"

[postgres]
Host=     "prod-load.cfbuweg6pdxe.us-east-1.rds.amazonaws.com"
Port=     5432
Username= "socialapplication"
Password= "socialapplication"
DBName=   "social"

[mq]
Host     = "brown-jaguar.rmq.cloudamqp.com"
Port     = 5672
Login    = "cadvyqxd"
Password = "yf29g7sn61dqSFqL7NlNbzC1NcXe9hIS"
Vhost    = "cadvyqxd"

[redis]
URL = "prod-test.1ia3pb.0001.use1.cache.amazonaws.com:6379"
DB  = 0

[email]
Host            = "prod.koding.com"
Protocol        = "http:"
DefaultFromMail = "hello@koding.com"
DefaultFromName = "Koding"
Username        = "koding"
Password        = "DEQl7_Dr"

[sitemap]
RedisDB = 0

[algolia]
AppId          = "DYVV81J2S1"
ApiKey         = "303eb858050b1067bcd704d6cbfb977c"
ApiSecretKey   = "041427512bcdcd0c7bd4899ec8175f46"
IndexSuffix    = ".load"

[mixpanel]
Enabled       = false
Token         = "113c2731b47a5151f4be44ddd5af0e7a"

[limits]
MessageBodyMinLen    = 1
PostThrottleDuration = "10s"
PostThrottleCount    = 100

EventExchangeName ="BrokerMessageBus"
DisableCaching    = false
Debug             = false

[stripe]
SecretToken = "sk_live_GlE3sUKT9TrDbSEAMCQXjeLh"
