EventExchangeName="BrokerMessageBus"
Mongo="10.208.228.10:27017/koding"
Environment="prod"

[postgres]
Host=     "10.208.228.10"
Port=     5432
# Username= "postgres"
# Password= "123123123"
Username= "socialapplication"
Password= "socialapplication"
DBName=   "social"

[mq]
Host=     "10.208.228.10"
Port=     5672
Username= "guest"
Password= "guest"
Vhost=    "/"


[redis]
URL ="10.208.228.10:6379"
DB  =0


[limits]
MessageBodyMinLen=1

[Notification]
CacheEnabled = false

[emailnotification]
templateRoot="workers/emailnotifier/templates/"

[sendgrid]
Username=        "koding"
Password=        "DEQl7_Dr"
FromName=        "Koding"
FromMail=        "hello@koding.com"
ForcedRecipient= "canthefason@gmail.com"
