EventExchangeName = "BrokerMessageBus"
Mongo             = "dev:k9lc4G1k32nyD72@172.16.10.36:27017/koding"
Environment       = "sandbox"
Uri               = "http://sandbox.koding.com"

[postgres]
Host     = "sandbox0.cfbuweg6pdxe.us-east-1.rds.amazonaws.com"
Port     = 5432
Username = "socialapplication"
Password = "socialapplication"
DBName   = "social"

[mq]
Host     = "172.16.6.14"
Port     = 5672
Username = "guest"
Password = "djfjfhgh4455__5"
Vhost    = "sandbox"

[redis]
URL    = "172.16.10.16:6379"
DB     = 0
# slave one is not used, just here for future ref
Slave= "172.16.10.17:6379"

[limits]
MessageBodyMinLen = 1

[Notification]
CacheEnabled = false

[emailnotification]
templateRoot = "go/src/socialapi/workers/emailnotifier/templates/"

[sendgrid]
Username= "koding"
Password= "DEQl7_Dr"
FromName= "Koding"
FromMail= "hello@koding.com"

[sitemap]
RedisDB= 1
