EventExchangeName = "BrokerMessageBus"
Mongo             = "dev:k9lc4G1k32nyD72@172.16.10.36:27017/koding"
Environment       = "sandbox"
Region            = "sandbox"
Uri               = "http://sandbox.koding.com"
DisableCaching    = false


[postgres]
# AWS
# Host     = "sandbox0.cfbuweg6pdxe.us-east-1.rds.amazonaws.com"
# Sandbox
Host     = "172.16.10.45"
Port     = 5432
Username = "socialapplication"
Password = "socialapplication"
DBName   = "social"

[mq]
Host     = "172.16.6.14"
Port     = 5672
Username = "guest"
Password = "djfjfhgh4455__5"
Vhost    = "sandbox"

[redis]
URL    = "172.16.10.16:6379"
DB     = 0
# slave one is not used, just here for future ref
Slave= "172.16.10.17:6379"

[limits]
MessageBodyMinLen    = 1
PostThrottleDuration = "15s"
PostThrottleCount    = 3


[emailnotification]
templateRoot = "go/src/socialapi/workers/emailnotifier/templates/"

[sendgrid]
Username= "koding"
Password= "DEQl7_Dr"
FromName= "Koding"
FromMail= "hello@koding.com"

[sitemap]
RedisDB= 1

[algolia]
AppId          = "8KD9RHY1OA"
ApiKey         = "1ceb41897600d8df196eb22a3528eb5f"
ReadOnlyApiKey = "e4a8ebe91bf848b67c9ac31a6178c64b"
IndexSuffix    = ".sandbox"

[analytics]
Enabled       = false
MixpanelToken = "113c2731b47a5151f4be44ddd5af0e7a"
