EventExchangeName = "BrokerMessageBus"
Mongo             = "dev:k9lc4G1k32nyD72@172.16.3.9:27017/koding"
Environment       = "production"
Region            = "aws"
Uri               = "https://koding.com"
DisableCaching    = false


[postgres]
Host     = "prod0.cfbuweg6pdxe.us-east-1.rds.amazonaws.com"
Port     = 5432
Username = "socialapplication"
Password = "socialapplication"
DBName   = "social"

[mq]
Host     = "172.16.3.4"
Port     = 5672
Username = "guest"
Password = "Xah8ibeekelah"
Vhost    = "new"

[redis]
URL = "172.16.10.16:6379"
DB  = 0
# slave one is not used, just here for future ref
Slave=    "172.16.10.17:6379"

[limits]
MessageBodyMinLen    = 1
PostThrottleDuration = "15s"
PostThrottleCount    = 3


[emailnotification]
TemplateRoot = "go/src/socialapi/workers/emailnotifier/templates/"

[sendgrid]
Username = "koding"
Password = "DEQl7_Dr"
FromName = "Koding"
FromMail = "hello@koding.com"

[sitemap]
RedisDB= 1

[algolia]
AppId          = "DYVV81J2S1"
ApiKey         = "041427512bcdcd0c7bd4899ec8175f46"
ReadOnlyApiKey = "303eb858050b1067bcd704d6cbfb977c"
IndexSuffix    = ""
