[postgres]
Host=     "localhost"
Port=     5432
Username= "socialapplication"
Password= "socialapplication"
DBName=   "social"

[mq]
Host     = "localhost"
Port     = 5672
Login    = "guest"
Password = "guest"
Vhost    = "/"

[redis]
URL = "localhost:6379"
DB  = 0

Mongo              = "localhost:27017/koding"

Environment        = "test"

Region             = "test"

Hostname           = "http://lvh.me:8090"

[email]
Host            = "lvh.me:8090"
Protocol        = "http:"
DefaultFromMail = "hello@koding.com"
DefaultFromName = "Koding"
ForcedRecipient = "canthefason@gmail.com"
Username        = "koding"
Password        = "DEQl7_Dr"

[sitemap]
RedisDB = 2

[algolia]
AppId          = "DYVV81J2S1"
ApiKey         = "303eb858050b1067bcd704d6cbfb977c"
ApiSecretKey   = "041427512bcdcd0c7bd4899ec8175f46"
IndexSuffix    = ".test"

[mixpanel]
Enabled       = false
Token         = "113c2731b47a5151f4be44ddd5af0e7a"

[limits]
MessageBodyMinLen    = 1
PostThrottleDuration = "10s"
PostThrottleCount    = 100

EventExchangeName ="BrokerMessageBus"
DisableCaching    = false
Debug             = false

[stripe]
secretToken = "sk_test_2ix1eKPy8WtfWTLecG9mPOvN"

[paypal]
Username  = "senthil+1_api1.koding.com"
Password  = "JFH6LXW97QN588RC"
Signature = "AFcWxV21C7fd0v3bYYYRCpSSRl31AjnvzeXiWRC89GOtfhnGMSsO563z"
ReturnUrl = "/-/payments/paypal/return"
CancelUrl = "/-/payments/paypal/cancel"

[gatekeeper]
host = "localhost"
port = 7200

[gatekeeper.pubnub]
publishkey = "pub-c-ed2a8027-1f8a-4070-b0ec-d4ad535435f6"
subscribekey = "sub-c-00d2be66-8867-11e4-9b60-02ee2ddab7fe"
secretkey = "sec-c-Mzg5ZTMzOTAtYjQxOC00YTc5LWJkNWEtZmI3NTk3ODA5YzAx"
serverAuthKey = "689b3039-439e-4ca6-80c2-3b0b17e3f2f3b3736a37-554c-44a1-86d4-45099a98c11a"
origin = "pubsub.pubnub.com"
enabled = true

[customDomain]
public = "https://koding-siesta.ngrok.com"
public_ = "koding-siesta.ngrok.com"
local = "http://127.0.0.1:8090"
local_ = "127.0.0.1:8090"
host = "http://lvh.me"
port = 8090

[kloud]
SecretKey  = "J7suqUXhqXeiLchTrBDvovoJZEBVPxncdHyHCYqnGfY4HirKCe"
Address    = "http://localhost:5500/kite"

[paymentwebhook]
port = "6600"

[googleapiServiceAccount]
clientId = "753589381435-irpve47dabrj9sjiqqdo2k9tr8l1jn5v.apps.googleusercontent.com"
clientSecret = "1iNPDf8-F9bTKmX8OWXlkYra"
serviceAccountEmail = "753589381435-irpve47dabrj9sjiqqdo2k9tr8l1jn5v@developer.gserviceaccount.com"
serviceAccountKeyFile = "/pipeline/build/keys/googleapi-privatekey.pem"

geoipdbpath = "/pipeline/build/go/geoipdb"