EventExchangeName  = "BrokerMessageBus"
Mongo              = "localhost:27017/koding"
Environment        = "vagrant"
Region             = "vagrant"
Uri                = "http://lvh.me:3020"
DisableCaching     = false

[postgres]
Host         = "localhost"
Port         = 5432
Username     = "socialapplication"
Password     = "socialapplication"
DBName       = "social"

[mq]
Host       = "localhost"
Port       = 5672
Username   = "PROD-k5it50s4676pO9O"
Password   = "djfjfhgh4455__5"
Vhost      =  "/"

[redis]
URL = "localhost:6379"
DB  = 0

[limits]
MessageBodyMinLen    = 1
PostThrottleDuration = "5s"
PostThrottleCount    = 20

[emailnotification]
TemplateRoot = "workers/emailnotifier/templates/"

[sendgrid]
Username        = "koding"
Password        = "DEQl7_Dr"
FromName        = "Koding"
FromMail        = "hello@koding.com"
ForcedRecipient = "canthefason@gmail.com"

[sitemap]
XMLRoot = "workers/sitemap/files/"
RedisDB = 1

[algolia]
AppId          = "DYVV81J2S1"
ApiKey         = "041427512bcdcd0c7bd4899ec8175f46"
ReadOnlyApiKey = "303eb858050b1067bcd704d6cbfb977c"
IndexSuffix    = ".vagrant"
