EventExchangeName="BrokerMessageBus"
Mongo="localhost:27017/koding"

[postgres]
Host=     "localhost"
Port=     5432
Username= "postgres"
Password= "123123123"
DBName=   "social"

[mq]
Host=     "localhost"
Port=     5672
Username= "PROD-k5it50s4676pO9O"
Password= "djfjfhgh4455__5"
Vhost=    "/"
