title: Modern Dev Environment Delivered Â· Koding
email: support@koding.com
repository: https://github.com/koding/koding
description: >
  Instantly create, share, scale, and manage development environments.
keywords: >
  integrated development environment, cloud ide, dev environment,
  cloud development environment, cloud editor, virtual dev environment,
  web based ide, test environment, docker, aws, vagrant, azure, rackspace
baseurl: ""
url: "https://www.koding.com"
permalink: /blog/:year/:month/:title/
paginate_path: "/blog/page/:num"
paginate: 5
timezone: America/Los_Angeles
exclude:
- Gemfile
- Gemfile.lock
- README.md
- Rakefile
- vendor/bundle
- docs/github.com.terraform
- docs/terraform/commands
- docs/terraform/configuration/atlas.html.md
- docs/terraform/configuration/modules.html.md
- docs/terraform/import
- docs/terraform/internals
- docs/terraform/state
- docs/terraform/modules
- docs/terraform/plugins

gems:
- jekyll-paginate
- jekyll-redirect-from
sass:
  style: compressed
  sass_dir: _css
social:
  twitter: https://twitter.com/koding
  github:  https://github.com/koding
  facebook:  https://facebook.com/koding
  linkedin:  https://linkedin.com/company/koding
social_images:
  twitter: /assets/img/social/share.tw.jpg
  google: /assets/img/social/share.g+.jpg
  facebook: /assets/img/social/share.fb.jpg
