language: go
go:
- tip
install:
- go get code.google.com/p/go.tools/cmd/cover
- go get github.com/hailiang/goveralls
script:
- cd algoliasearch
- go test -covermode=count -coverprofile=profile.cov
after_script:
- export PATH=$PATH:$HOME/gopath/bin/
- cd algoliasearch
- goveralls -coverprofile=profile.cov -service=travis-ci
env:
  global:
  - secure: AEx3yI/ilyxnTHRlucdk+tmGeiRN4khKqdWzK9BUtUBb4tI/V7GJmXah9ua5tAa1Tsus0LQYtH3W6YQIf2K6D/Qoer2Hyg/uuYKNfMKpU9D8kxGOUwe5UaeOsevmPALqvc3xblmFmff1VzCsuuktxa5d/DuM/N+bOd5e5OB0kjM=
  - secure: fHMFoC/7J8A39IPnr0sJ0r3GQ9Ow7afffZafBBsBGP2NbFRXR6nnqBNAJpNPodixHPU2wu/oP/bpMUWSTdV86ZDcYKk6GsGiJFXPox9kfqJgAO6DpBELbSmTDaw/TIXEtJCu1NyQWT6dCz1ovTGg/QCqrsLNHqx0dsJkcRbx5b8=
